# spring.data.mongodb.database=movie_db
# spring.data.mongodb.uri=mongodb+srv://jasvickglams_db_user:<db_password>@cluster0.e8vtw9k.mongodb.net/

spring.data.mongodb.database=movie_db
spring.data.mongodb.uri=${MONGODB_URI}